#docker run -p 8545:8545 -p 8546:8546 -p 30303:30303 hyperledger/besu:latest --rpc-http-enabled --rpc-ws-enabled

services:

  rpc-node:
    container_name: rpc-node
    image: hyperledger/besu:24.7.0
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
      - 30303:30303/tcp
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/rpcnode:/opt/besu/keys
    networks:
      besu:
        ipv4_address: 172.16.239.15
    entrypoint: besu --rpc-http-enabled --rpc-ws-enabled --config-file=/config/config.toml


  member1:
    container_name: member-1
    image: hyperledger/besu:24.7.0
    ports:
      - 21001:8545/tcp
      - 30303
      - 9545
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator1:/opt/besu/keys
    networks:
      besu:
        ipv4_address: 172.16.239.11
    entrypoint: besu --config-file=/config/config.toml



networks:
  besu:
    name: besu
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
