
services:

  rpc-node:
    container_name: rpc-node
    image: hyperledger/besu:24.7.0
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
    volumes:
      - ./config/besu/:/config
      - ./config/keys/rpc-node:/opt/besu/keys
      - ./logs/:/tmp/besu
    networks:
      besu:
        ipv4_address: 172.16.239.10
    entrypoint: besu --config-file=/config/config.toml --p2p-host=172.16.239.10


  validator1:
    container_name: validator-1
    image: hyperledger/besu:24.7.0
    ports:
      - 21001:8545/tcp
      - 30303
      - 9545
    volumes:
      - ./config/besu/:/config
      - ./config/keys/validator1:/opt/besu/keys
      - ./logs/:/tmp/besu
    networks:
      besu:
        ipv4_address: 172.16.239.11
    entrypoint: besu --config-file=/config/config.toml --p2p-host=172.16.239.11


  validator2:
    container_name: validator-2
    image: hyperledger/besu:24.7.0
    ports:
      - 21002:8545/tcp
      - 30303
      - 9545
    volumes:
      - ./config/besu/:/config
      - ./config/keys/validator2:/opt/besu/keys
      - ./logs/:/tmp/besu
    networks:
      besu:
        ipv4_address: 172.16.239.12
    entrypoint: besu --config-file=/config/config.toml --p2p-host=172.16.239.12


  member1:
    container_name: member-1
    image: hyperledger/besu:24.7.0
    ports:
      - 20001:8545/tcp
      - 30303
      - 9545
    volumes:
      - ./config/besu/:/config
      - ./config/keys/member1:/opt/besu/keys
      - ./logs/:/tmp/besu
    networks:
      besu:
        ipv4_address: 172.16.239.13
    entrypoint: besu --config-file=/config/config.toml --p2p-host=172.16.239.13


  member2:
    container_name: member-2
    image: hyperledger/besu:24.7.0
    ports:
      - 20002:8545/tcp
      - 30303
      - 9545
    volumes:
      - ./config/besu/:/config
      - ./config/keys/member2:/opt/besu/keys
      - ./logs/:/tmp/besu
    networks:
      besu:
        ipv4_address: 172.16.239.14
    entrypoint: besu --config-file=/config/config.toml --p2p-host=172.16.239.14


  eth-signer:
    container_name: eth-signer
    image: consensys/ethsigner:23.6
    depends_on:
      - rpc-node
    ports:
    - 8545
    volumes:
      - ./config/keys/eth-signer/accountKeystore:/opt/ethsigner/key
      - ./config/keys/eth-signer/accountPassword:/opt/ethsigner/password
    command: [
      "--chain-id=1337",
      "--http-listen-host=0.0.0.0",
      "--downstream-http-port=8545",
      "--downstream-http-host=rpc-node",
      "file-based-signer",
      "-k",
      "/opt/ethsigner/key",
      "-p",
      "/opt/ethsigner/password"
    ]
    networks:
      besu:
        ipv4_address: 172.16.239.20


networks:
  besu:
    name: besu
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
